# Project: Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.o
LINKOBJ  = Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.o: Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.cpp
	$(CPP) -c Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.cpp -o Skyrim_4_kameny_na_kazdym_3_symboly_volba_znaku.o $(CXXFLAGS)
